# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Datascribe"
license = "MIT"
licenselink = "https://github.com/chnm/datascribe-site/blob/master/themes/datascribe/LICENSE"
description = "Hugo theme for the DataScribe project for RRCHNM. Built using Foundation"
homepage = "https://github.com/chnm/datascribe-site"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "RRCHNM"
  homepage = "https://github.com/chnm"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
